# Generated by Django 2.0.5 on 2018-05-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=256)),
                ('refresh_token', models.CharField(max_length=256)),
                ('expiration_time', models.DateTimeField()),
            ],
        ),
    ]
